// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/survey/fhir.proto
// Protobuf Java Version: 4.32.0

package ondewo.survey;

@com.google.protobuf.Generated
public final class Fhir {
  private Fhir() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      Fhir.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateFHIRSurveyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ondewo.survey.CreateFHIRSurveyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * FHIR questionnaire on a gRPC Struct format
     * </pre>
     *
     * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     * @return Whether the fhirQuestionnaire field is set.
     */
    boolean hasFhirQuestionnaire();
    /**
     * <pre>
     * FHIR questionnaire on a gRPC Struct format
     * </pre>
     *
     * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     * @return The fhirQuestionnaire.
     */
    com.google.protobuf.Struct getFhirQuestionnaire();
    /**
     * <pre>
     * FHIR questionnaire on a gRPC Struct format
     * </pre>
     *
     * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     */
    com.google.protobuf.StructOrBuilder getFhirQuestionnaireOrBuilder();
  }
  /**
   * Protobuf type {@code ondewo.survey.CreateFHIRSurveyRequest}
   */
  public static final class CreateFHIRSurveyRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ondewo.survey.CreateFHIRSurveyRequest)
      CreateFHIRSurveyRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        CreateFHIRSurveyRequest.class.getName());
    }
    // Use CreateFHIRSurveyRequest.newBuilder() to construct.
    private CreateFHIRSurveyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CreateFHIRSurveyRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ondewo.survey.Fhir.internal_static_ondewo_survey_CreateFHIRSurveyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ondewo.survey.Fhir.internal_static_ondewo_survey_CreateFHIRSurveyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ondewo.survey.Fhir.CreateFHIRSurveyRequest.class, ondewo.survey.Fhir.CreateFHIRSurveyRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FHIR_QUESTIONNAIRE_FIELD_NUMBER = 1;
    private com.google.protobuf.Struct fhirQuestionnaire_;
    /**
     * <pre>
     * FHIR questionnaire on a gRPC Struct format
     * </pre>
     *
     * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     * @return Whether the fhirQuestionnaire field is set.
     */
    @java.lang.Override
    public boolean hasFhirQuestionnaire() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * FHIR questionnaire on a gRPC Struct format
     * </pre>
     *
     * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     * @return The fhirQuestionnaire.
     */
    @java.lang.Override
    public com.google.protobuf.Struct getFhirQuestionnaire() {
      return fhirQuestionnaire_ == null ? com.google.protobuf.Struct.getDefaultInstance() : fhirQuestionnaire_;
    }
    /**
     * <pre>
     * FHIR questionnaire on a gRPC Struct format
     * </pre>
     *
     * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getFhirQuestionnaireOrBuilder() {
      return fhirQuestionnaire_ == null ? com.google.protobuf.Struct.getDefaultInstance() : fhirQuestionnaire_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getFhirQuestionnaire());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFhirQuestionnaire());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ondewo.survey.Fhir.CreateFHIRSurveyRequest)) {
        return super.equals(obj);
      }
      ondewo.survey.Fhir.CreateFHIRSurveyRequest other = (ondewo.survey.Fhir.CreateFHIRSurveyRequest) obj;

      if (hasFhirQuestionnaire() != other.hasFhirQuestionnaire()) return false;
      if (hasFhirQuestionnaire()) {
        if (!getFhirQuestionnaire()
            .equals(other.getFhirQuestionnaire())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFhirQuestionnaire()) {
        hash = (37 * hash) + FHIR_QUESTIONNAIRE_FIELD_NUMBER;
        hash = (53 * hash) + getFhirQuestionnaire().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ondewo.survey.Fhir.CreateFHIRSurveyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ondewo.survey.CreateFHIRSurveyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ondewo.survey.CreateFHIRSurveyRequest)
        ondewo.survey.Fhir.CreateFHIRSurveyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ondewo.survey.Fhir.internal_static_ondewo_survey_CreateFHIRSurveyRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ondewo.survey.Fhir.internal_static_ondewo_survey_CreateFHIRSurveyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ondewo.survey.Fhir.CreateFHIRSurveyRequest.class, ondewo.survey.Fhir.CreateFHIRSurveyRequest.Builder.class);
      }

      // Construct using ondewo.survey.Fhir.CreateFHIRSurveyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetFhirQuestionnaireFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fhirQuestionnaire_ = null;
        if (fhirQuestionnaireBuilder_ != null) {
          fhirQuestionnaireBuilder_.dispose();
          fhirQuestionnaireBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ondewo.survey.Fhir.internal_static_ondewo_survey_CreateFHIRSurveyRequest_descriptor;
      }

      @java.lang.Override
      public ondewo.survey.Fhir.CreateFHIRSurveyRequest getDefaultInstanceForType() {
        return ondewo.survey.Fhir.CreateFHIRSurveyRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ondewo.survey.Fhir.CreateFHIRSurveyRequest build() {
        ondewo.survey.Fhir.CreateFHIRSurveyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ondewo.survey.Fhir.CreateFHIRSurveyRequest buildPartial() {
        ondewo.survey.Fhir.CreateFHIRSurveyRequest result = new ondewo.survey.Fhir.CreateFHIRSurveyRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ondewo.survey.Fhir.CreateFHIRSurveyRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fhirQuestionnaire_ = fhirQuestionnaireBuilder_ == null
              ? fhirQuestionnaire_
              : fhirQuestionnaireBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ondewo.survey.Fhir.CreateFHIRSurveyRequest) {
          return mergeFrom((ondewo.survey.Fhir.CreateFHIRSurveyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ondewo.survey.Fhir.CreateFHIRSurveyRequest other) {
        if (other == ondewo.survey.Fhir.CreateFHIRSurveyRequest.getDefaultInstance()) return this;
        if (other.hasFhirQuestionnaire()) {
          mergeFhirQuestionnaire(other.getFhirQuestionnaire());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetFhirQuestionnaireFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Struct fhirQuestionnaire_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> fhirQuestionnaireBuilder_;
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       * @return Whether the fhirQuestionnaire field is set.
       */
      public boolean hasFhirQuestionnaire() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       * @return The fhirQuestionnaire.
       */
      public com.google.protobuf.Struct getFhirQuestionnaire() {
        if (fhirQuestionnaireBuilder_ == null) {
          return fhirQuestionnaire_ == null ? com.google.protobuf.Struct.getDefaultInstance() : fhirQuestionnaire_;
        } else {
          return fhirQuestionnaireBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       */
      public Builder setFhirQuestionnaire(com.google.protobuf.Struct value) {
        if (fhirQuestionnaireBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fhirQuestionnaire_ = value;
        } else {
          fhirQuestionnaireBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       */
      public Builder setFhirQuestionnaire(
          com.google.protobuf.Struct.Builder builderForValue) {
        if (fhirQuestionnaireBuilder_ == null) {
          fhirQuestionnaire_ = builderForValue.build();
        } else {
          fhirQuestionnaireBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       */
      public Builder mergeFhirQuestionnaire(com.google.protobuf.Struct value) {
        if (fhirQuestionnaireBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            fhirQuestionnaire_ != null &&
            fhirQuestionnaire_ != com.google.protobuf.Struct.getDefaultInstance()) {
            getFhirQuestionnaireBuilder().mergeFrom(value);
          } else {
            fhirQuestionnaire_ = value;
          }
        } else {
          fhirQuestionnaireBuilder_.mergeFrom(value);
        }
        if (fhirQuestionnaire_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       */
      public Builder clearFhirQuestionnaire() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fhirQuestionnaire_ = null;
        if (fhirQuestionnaireBuilder_ != null) {
          fhirQuestionnaireBuilder_.dispose();
          fhirQuestionnaireBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       */
      public com.google.protobuf.Struct.Builder getFhirQuestionnaireBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetFhirQuestionnaireFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       */
      public com.google.protobuf.StructOrBuilder getFhirQuestionnaireOrBuilder() {
        if (fhirQuestionnaireBuilder_ != null) {
          return fhirQuestionnaireBuilder_.getMessageOrBuilder();
        } else {
          return fhirQuestionnaire_ == null ?
              com.google.protobuf.Struct.getDefaultInstance() : fhirQuestionnaire_;
        }
      }
      /**
       * <pre>
       * FHIR questionnaire on a gRPC Struct format
       * </pre>
       *
       * <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
          internalGetFhirQuestionnaireFieldBuilder() {
        if (fhirQuestionnaireBuilder_ == null) {
          fhirQuestionnaireBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                  getFhirQuestionnaire(),
                  getParentForChildren(),
                  isClean());
          fhirQuestionnaire_ = null;
        }
        return fhirQuestionnaireBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ondewo.survey.CreateFHIRSurveyRequest)
    }

    // @@protoc_insertion_point(class_scope:ondewo.survey.CreateFHIRSurveyRequest)
    private static final ondewo.survey.Fhir.CreateFHIRSurveyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ondewo.survey.Fhir.CreateFHIRSurveyRequest();
    }

    public static ondewo.survey.Fhir.CreateFHIRSurveyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateFHIRSurveyRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateFHIRSurveyRequest>() {
      @java.lang.Override
      public CreateFHIRSurveyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreateFHIRSurveyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateFHIRSurveyRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ondewo.survey.Fhir.CreateFHIRSurveyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SurveyFHIRAnswersResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ondewo.survey.SurveyFHIRAnswersResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/&lt;Project ID&gt;/agent`.
     * </pre>
     *
     * <code>string survey_id = 1;</code>
     * @return The surveyId.
     */
    java.lang.String getSurveyId();
    /**
     * <pre>
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/&lt;Project ID&gt;/agent`.
     * </pre>
     *
     * <code>string survey_id = 1;</code>
     * @return The bytes for surveyId.
     */
    com.google.protobuf.ByteString
        getSurveyIdBytes();

    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    java.util.List<com.google.protobuf.Struct> 
        getFhirQuestionnaireResponsesList();
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    com.google.protobuf.Struct getFhirQuestionnaireResponses(int index);
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    int getFhirQuestionnaireResponsesCount();
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    java.util.List<? extends com.google.protobuf.StructOrBuilder> 
        getFhirQuestionnaireResponsesOrBuilderList();
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    com.google.protobuf.StructOrBuilder getFhirQuestionnaireResponsesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ondewo.survey.SurveyFHIRAnswersResponse}
   */
  public static final class SurveyFHIRAnswersResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ondewo.survey.SurveyFHIRAnswersResponse)
      SurveyFHIRAnswersResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        SurveyFHIRAnswersResponse.class.getName());
    }
    // Use SurveyFHIRAnswersResponse.newBuilder() to construct.
    private SurveyFHIRAnswersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SurveyFHIRAnswersResponse() {
      surveyId_ = "";
      fhirQuestionnaireResponses_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ondewo.survey.Fhir.internal_static_ondewo_survey_SurveyFHIRAnswersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ondewo.survey.Fhir.internal_static_ondewo_survey_SurveyFHIRAnswersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ondewo.survey.Fhir.SurveyFHIRAnswersResponse.class, ondewo.survey.Fhir.SurveyFHIRAnswersResponse.Builder.class);
    }

    public static final int SURVEY_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object surveyId_ = "";
    /**
     * <pre>
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/&lt;Project ID&gt;/agent`.
     * </pre>
     *
     * <code>string survey_id = 1;</code>
     * @return The surveyId.
     */
    @java.lang.Override
    public java.lang.String getSurveyId() {
      java.lang.Object ref = surveyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surveyId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/&lt;Project ID&gt;/agent`.
     * </pre>
     *
     * <code>string survey_id = 1;</code>
     * @return The bytes for surveyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurveyIdBytes() {
      java.lang.Object ref = surveyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surveyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FHIR_QUESTIONNAIRE_RESPONSES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.Struct> fhirQuestionnaireResponses_;
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.Struct> getFhirQuestionnaireResponsesList() {
      return fhirQuestionnaireResponses_;
    }
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.protobuf.StructOrBuilder> 
        getFhirQuestionnaireResponsesOrBuilderList() {
      return fhirQuestionnaireResponses_;
    }
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    @java.lang.Override
    public int getFhirQuestionnaireResponsesCount() {
      return fhirQuestionnaireResponses_.size();
    }
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Struct getFhirQuestionnaireResponses(int index) {
      return fhirQuestionnaireResponses_.get(index);
    }
    /**
     * <pre>
     * all requested answers
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getFhirQuestionnaireResponsesOrBuilder(
        int index) {
      return fhirQuestionnaireResponses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(surveyId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, surveyId_);
      }
      for (int i = 0; i < fhirQuestionnaireResponses_.size(); i++) {
        output.writeMessage(2, fhirQuestionnaireResponses_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(surveyId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, surveyId_);
      }
      for (int i = 0; i < fhirQuestionnaireResponses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, fhirQuestionnaireResponses_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ondewo.survey.Fhir.SurveyFHIRAnswersResponse)) {
        return super.equals(obj);
      }
      ondewo.survey.Fhir.SurveyFHIRAnswersResponse other = (ondewo.survey.Fhir.SurveyFHIRAnswersResponse) obj;

      if (!getSurveyId()
          .equals(other.getSurveyId())) return false;
      if (!getFhirQuestionnaireResponsesList()
          .equals(other.getFhirQuestionnaireResponsesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SURVEY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSurveyId().hashCode();
      if (getFhirQuestionnaireResponsesCount() > 0) {
        hash = (37 * hash) + FHIR_QUESTIONNAIRE_RESPONSES_FIELD_NUMBER;
        hash = (53 * hash) + getFhirQuestionnaireResponsesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ondewo.survey.Fhir.SurveyFHIRAnswersResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ondewo.survey.SurveyFHIRAnswersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ondewo.survey.SurveyFHIRAnswersResponse)
        ondewo.survey.Fhir.SurveyFHIRAnswersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ondewo.survey.Fhir.internal_static_ondewo_survey_SurveyFHIRAnswersResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ondewo.survey.Fhir.internal_static_ondewo_survey_SurveyFHIRAnswersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ondewo.survey.Fhir.SurveyFHIRAnswersResponse.class, ondewo.survey.Fhir.SurveyFHIRAnswersResponse.Builder.class);
      }

      // Construct using ondewo.survey.Fhir.SurveyFHIRAnswersResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        surveyId_ = "";
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          fhirQuestionnaireResponses_ = java.util.Collections.emptyList();
        } else {
          fhirQuestionnaireResponses_ = null;
          fhirQuestionnaireResponsesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ondewo.survey.Fhir.internal_static_ondewo_survey_SurveyFHIRAnswersResponse_descriptor;
      }

      @java.lang.Override
      public ondewo.survey.Fhir.SurveyFHIRAnswersResponse getDefaultInstanceForType() {
        return ondewo.survey.Fhir.SurveyFHIRAnswersResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ondewo.survey.Fhir.SurveyFHIRAnswersResponse build() {
        ondewo.survey.Fhir.SurveyFHIRAnswersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ondewo.survey.Fhir.SurveyFHIRAnswersResponse buildPartial() {
        ondewo.survey.Fhir.SurveyFHIRAnswersResponse result = new ondewo.survey.Fhir.SurveyFHIRAnswersResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ondewo.survey.Fhir.SurveyFHIRAnswersResponse result) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            fhirQuestionnaireResponses_ = java.util.Collections.unmodifiableList(fhirQuestionnaireResponses_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.fhirQuestionnaireResponses_ = fhirQuestionnaireResponses_;
        } else {
          result.fhirQuestionnaireResponses_ = fhirQuestionnaireResponsesBuilder_.build();
        }
      }

      private void buildPartial0(ondewo.survey.Fhir.SurveyFHIRAnswersResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.surveyId_ = surveyId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ondewo.survey.Fhir.SurveyFHIRAnswersResponse) {
          return mergeFrom((ondewo.survey.Fhir.SurveyFHIRAnswersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ondewo.survey.Fhir.SurveyFHIRAnswersResponse other) {
        if (other == ondewo.survey.Fhir.SurveyFHIRAnswersResponse.getDefaultInstance()) return this;
        if (!other.getSurveyId().isEmpty()) {
          surveyId_ = other.surveyId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          if (!other.fhirQuestionnaireResponses_.isEmpty()) {
            if (fhirQuestionnaireResponses_.isEmpty()) {
              fhirQuestionnaireResponses_ = other.fhirQuestionnaireResponses_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFhirQuestionnaireResponsesIsMutable();
              fhirQuestionnaireResponses_.addAll(other.fhirQuestionnaireResponses_);
            }
            onChanged();
          }
        } else {
          if (!other.fhirQuestionnaireResponses_.isEmpty()) {
            if (fhirQuestionnaireResponsesBuilder_.isEmpty()) {
              fhirQuestionnaireResponsesBuilder_.dispose();
              fhirQuestionnaireResponsesBuilder_ = null;
              fhirQuestionnaireResponses_ = other.fhirQuestionnaireResponses_;
              bitField0_ = (bitField0_ & ~0x00000002);
              fhirQuestionnaireResponsesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetFhirQuestionnaireResponsesFieldBuilder() : null;
            } else {
              fhirQuestionnaireResponsesBuilder_.addAllMessages(other.fhirQuestionnaireResponses_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                surveyId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.Struct m =
                    input.readMessage(
                        com.google.protobuf.Struct.parser(),
                        extensionRegistry);
                if (fhirQuestionnaireResponsesBuilder_ == null) {
                  ensureFhirQuestionnaireResponsesIsMutable();
                  fhirQuestionnaireResponses_.add(m);
                } else {
                  fhirQuestionnaireResponsesBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object surveyId_ = "";
      /**
       * <pre>
       * The project identifier for this survey. Equal to the parent of the corresponding Agent.
       * Format: `projects/&lt;Project ID&gt;/agent`.
       * </pre>
       *
       * <code>string survey_id = 1;</code>
       * @return The surveyId.
       */
      public java.lang.String getSurveyId() {
        java.lang.Object ref = surveyId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          surveyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The project identifier for this survey. Equal to the parent of the corresponding Agent.
       * Format: `projects/&lt;Project ID&gt;/agent`.
       * </pre>
       *
       * <code>string survey_id = 1;</code>
       * @return The bytes for surveyId.
       */
      public com.google.protobuf.ByteString
          getSurveyIdBytes() {
        java.lang.Object ref = surveyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surveyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The project identifier for this survey. Equal to the parent of the corresponding Agent.
       * Format: `projects/&lt;Project ID&gt;/agent`.
       * </pre>
       *
       * <code>string survey_id = 1;</code>
       * @param value The surveyId to set.
       * @return This builder for chaining.
       */
      public Builder setSurveyId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        surveyId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The project identifier for this survey. Equal to the parent of the corresponding Agent.
       * Format: `projects/&lt;Project ID&gt;/agent`.
       * </pre>
       *
       * <code>string survey_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSurveyId() {
        surveyId_ = getDefaultInstance().getSurveyId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The project identifier for this survey. Equal to the parent of the corresponding Agent.
       * Format: `projects/&lt;Project ID&gt;/agent`.
       * </pre>
       *
       * <code>string survey_id = 1;</code>
       * @param value The bytes for surveyId to set.
       * @return This builder for chaining.
       */
      public Builder setSurveyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        surveyId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Struct> fhirQuestionnaireResponses_ =
        java.util.Collections.emptyList();
      private void ensureFhirQuestionnaireResponsesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          fhirQuestionnaireResponses_ = new java.util.ArrayList<com.google.protobuf.Struct>(fhirQuestionnaireResponses_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> fhirQuestionnaireResponsesBuilder_;

      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public java.util.List<com.google.protobuf.Struct> getFhirQuestionnaireResponsesList() {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fhirQuestionnaireResponses_);
        } else {
          return fhirQuestionnaireResponsesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public int getFhirQuestionnaireResponsesCount() {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          return fhirQuestionnaireResponses_.size();
        } else {
          return fhirQuestionnaireResponsesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public com.google.protobuf.Struct getFhirQuestionnaireResponses(int index) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          return fhirQuestionnaireResponses_.get(index);
        } else {
          return fhirQuestionnaireResponsesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder setFhirQuestionnaireResponses(
          int index, com.google.protobuf.Struct value) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFhirQuestionnaireResponsesIsMutable();
          fhirQuestionnaireResponses_.set(index, value);
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder setFhirQuestionnaireResponses(
          int index, com.google.protobuf.Struct.Builder builderForValue) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          ensureFhirQuestionnaireResponsesIsMutable();
          fhirQuestionnaireResponses_.set(index, builderForValue.build());
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder addFhirQuestionnaireResponses(com.google.protobuf.Struct value) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFhirQuestionnaireResponsesIsMutable();
          fhirQuestionnaireResponses_.add(value);
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder addFhirQuestionnaireResponses(
          int index, com.google.protobuf.Struct value) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFhirQuestionnaireResponsesIsMutable();
          fhirQuestionnaireResponses_.add(index, value);
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder addFhirQuestionnaireResponses(
          com.google.protobuf.Struct.Builder builderForValue) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          ensureFhirQuestionnaireResponsesIsMutable();
          fhirQuestionnaireResponses_.add(builderForValue.build());
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder addFhirQuestionnaireResponses(
          int index, com.google.protobuf.Struct.Builder builderForValue) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          ensureFhirQuestionnaireResponsesIsMutable();
          fhirQuestionnaireResponses_.add(index, builderForValue.build());
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder addAllFhirQuestionnaireResponses(
          java.lang.Iterable<? extends com.google.protobuf.Struct> values) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          ensureFhirQuestionnaireResponsesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fhirQuestionnaireResponses_);
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder clearFhirQuestionnaireResponses() {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          fhirQuestionnaireResponses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public Builder removeFhirQuestionnaireResponses(int index) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          ensureFhirQuestionnaireResponsesIsMutable();
          fhirQuestionnaireResponses_.remove(index);
          onChanged();
        } else {
          fhirQuestionnaireResponsesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public com.google.protobuf.Struct.Builder getFhirQuestionnaireResponsesBuilder(
          int index) {
        return internalGetFhirQuestionnaireResponsesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public com.google.protobuf.StructOrBuilder getFhirQuestionnaireResponsesOrBuilder(
          int index) {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          return fhirQuestionnaireResponses_.get(index);  } else {
          return fhirQuestionnaireResponsesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public java.util.List<? extends com.google.protobuf.StructOrBuilder> 
           getFhirQuestionnaireResponsesOrBuilderList() {
        if (fhirQuestionnaireResponsesBuilder_ != null) {
          return fhirQuestionnaireResponsesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fhirQuestionnaireResponses_);
        }
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public com.google.protobuf.Struct.Builder addFhirQuestionnaireResponsesBuilder() {
        return internalGetFhirQuestionnaireResponsesFieldBuilder().addBuilder(
            com.google.protobuf.Struct.getDefaultInstance());
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public com.google.protobuf.Struct.Builder addFhirQuestionnaireResponsesBuilder(
          int index) {
        return internalGetFhirQuestionnaireResponsesFieldBuilder().addBuilder(
            index, com.google.protobuf.Struct.getDefaultInstance());
      }
      /**
       * <pre>
       * all requested answers
       * </pre>
       *
       * <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
       */
      public java.util.List<com.google.protobuf.Struct.Builder> 
           getFhirQuestionnaireResponsesBuilderList() {
        return internalGetFhirQuestionnaireResponsesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
          internalGetFhirQuestionnaireResponsesFieldBuilder() {
        if (fhirQuestionnaireResponsesBuilder_ == null) {
          fhirQuestionnaireResponsesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                  fhirQuestionnaireResponses_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          fhirQuestionnaireResponses_ = null;
        }
        return fhirQuestionnaireResponsesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ondewo.survey.SurveyFHIRAnswersResponse)
    }

    // @@protoc_insertion_point(class_scope:ondewo.survey.SurveyFHIRAnswersResponse)
    private static final ondewo.survey.Fhir.SurveyFHIRAnswersResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ondewo.survey.Fhir.SurveyFHIRAnswersResponse();
    }

    public static ondewo.survey.Fhir.SurveyFHIRAnswersResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SurveyFHIRAnswersResponse>
        PARSER = new com.google.protobuf.AbstractParser<SurveyFHIRAnswersResponse>() {
      @java.lang.Override
      public SurveyFHIRAnswersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SurveyFHIRAnswersResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SurveyFHIRAnswersResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ondewo.survey.Fhir.SurveyFHIRAnswersResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ondewo_survey_CreateFHIRSurveyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ondewo_survey_CreateFHIRSurveyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ondewo_survey_SurveyFHIRAnswersResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ondewo_survey_SurveyFHIRAnswersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ondewo/survey/fhir.proto\022\rondewo.surve" +
      "y\032\034google/api/annotations.proto\032\032ondewo/" +
      "survey/survey.proto\032\034google/protobuf/str" +
      "uct.proto\"N\n\027CreateFHIRSurveyRequest\0223\n\022" +
      "fhir_questionnaire\030\001 \001(\0132\027.google.protob" +
      "uf.Struct\"m\n\031SurveyFHIRAnswersResponse\022\021" +
      "\n\tsurvey_id\030\001 \001(\t\022=\n\034fhir_questionnaire_" +
      "responses\030\002 \003(\0132\027.google.protobuf.Struct" +
      "2\265\003\n\004FHIR\022j\n\020CreateFHIRSurvey\022&.ondewo.s" +
      "urvey.CreateFHIRSurveyRequest\032\025.ondewo.s" +
      "urvey.Survey\"\027\202\323\344\223\002\021\"\014/fhir_survey:\001*\022\243\001" +
      "\n\024GetFHIRSurveyAnswers\022&.ondewo.survey.G" +
      "etSurveyAnswersRequest\032(.ondewo.survey.S" +
      "urveyFHIRAnswersResponse\"9\202\323\344\223\0023\0221/surve" +
      "y/{survey_id=*}/fhir_answers/{session_id" +
      "=*}\022\232\001\n\027GetAllFHIRSurveyAnswers\022).ondewo" +
      ".survey.GetAllSurveyAnswersRequest\032(.ond" +
      "ewo.survey.SurveyFHIRAnswersResponse\"*\202\323" +
      "\344\223\002$\022\"/survey/{survey_id=*}/fhir_answers" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          ondewo.survey.SurveyOuterClass.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_ondewo_survey_CreateFHIRSurveyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ondewo_survey_CreateFHIRSurveyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ondewo_survey_CreateFHIRSurveyRequest_descriptor,
        new java.lang.String[] { "FhirQuestionnaire", });
    internal_static_ondewo_survey_SurveyFHIRAnswersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ondewo_survey_SurveyFHIRAnswersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ondewo_survey_SurveyFHIRAnswersResponse_descriptor,
        new java.lang.String[] { "SurveyId", "FhirQuestionnaireResponses", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
    ondewo.survey.SurveyOuterClass.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
